# Generated by Django 5.2.9 on 2025-12-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_historicalm_userprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='theme',
            field=models.CharField(blank=True, db_column='theme', db_comment='UIテーマ', default='light', max_length=32, verbose_name='テーマ'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='theme',
            field=models.CharField(blank=True, db_column='theme', db_comment='UIテーマ', default='light', max_length=32, verbose_name='テーマ'),
        ),
    ]
